pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'sujitrepo45/auth-service'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: "main", credentialsId: 'github-cred', url: 'https://github.com/sujit1998/flipkart-platform.git'
            }
        }

        stage('Build') {
            steps {
                sh './mvnw clean package -DskipTests'
            }
        }


        stage('Docker Build & Push') {
            steps {
                withCredentials([usernamePassword(credentialsID: 'dockerhub-cred', usernameVariable: 'DOCKERHUB_USER', passwordVariable: 'DOCKERHUB_PASS')]){
                script {
                    def imageTag = "${DOCKER_IMAGE}:latest"
                    sh "docker build -t ${imageTag} ."
                    sh "docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASS}"
                    sh "docker push ${imageTag}"
                }
                }
            }
        }
    }
}
